title: File

accept:
  mime: image/*
  orientation: landscape

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          alt:
            type: text
          caption:
            type: text
