title: Product

columns:
  - width: 1/3
    sections:
      product_head:
        type: fields
        fields:
          title:
            type: text
          price:
            type: number
            step: .01
            required: true
          price_promotional_text:
            label: Price promotional text
            type: text
            help: E.g. "Special Preorder Price"
          compare_at_price:
            label: Compare at price
            type: number
            help: If the product is on sale or promotion, enter the original price here
          images:
            template: 
            - image
            type: files
            layout: cards
            size: tiny
            info: "{{ file.dimensions }}, {{ file.size }}"
            required: true
            image:
              ratio: 1/1


  - width: 2/3
    sections:
      product_body:
        type: fields
        fields:
          product_details_a:
            label: Product details A
            type: textarea
            width: 1/2
          product_details_b:
            label: Product details B
            type: textarea
            help: Use this field to enter additional product details if you wish to split into 2 columns
            width: 1/2
          shipping_details:
            label: Shipping information
            type: textarea
            width: 1/2
          description_long:
            label: Description (long)
            type: textarea
